[book]
title = "Shashank's Engineering Blog"
authors = ["Shashank Shekhar"]
description = "Bookmark this to keep an eye on my project/journey updates!"
language = "en"

[output.html]
additional-css = ["theme/custom.css"]
additional-js = ["theme/header.js", "mermaid.min.js", "mermaid-init.js"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html.playground]
editable = true
